#!/usr/bin/env python
import os

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    obj = bld(features = 'cxx cxxshlib')
    obj.source = '''
            interface.cc
            ardour_websockets.cc
            typed_value.cc
            state.cc
            message.cc
            client.cc
            component.cc
            mixer.cc
            transport.cc
            server.cc
            feedback.cc
            dispatcher.cc
            manifest.cc
            resources.cc
            json.cc
    '''
    obj.defines      = [ 'PACKAGE="ardour_websockets"' ]
    obj.defines     += [ 'ARDOURSURFACE_DLL_EXPORTS' ]
    obj.includes     = ['.', './websockets']
    obj.name         = 'libardour_websockets'
    obj.target       = 'ardour_websockets'
    obj.uselib       = 'GLIBMM XML WEBSOCKETS OPENSSL SIGCPP'
    # NOTE: this surface is deliberately toolkit-free (no ytk/ydk/gtkmm2ext, only
    # glibmm + boost + libwebsockets): it is the control *protocol* shared with
    # the web/mobile frontend, and must build where there is no GTK stack
    # (--no-tk-stack, wasm/mobile targets).  Do not add a toolkit dependency here;
    # put GUI-level code in gtk2_ardour or a separate surface instead.
    obj.use          = 'libardour libardour_cp libpbd'
    obj.install_path = os.path.join(bld.env['LIBDIR'], 'surfaces')

    if bld.env['build_target'] == 'mingw':
        obj.defines+= [ '_WIN32_WINNT=0x0601', 'WINVER=0x0601' ]
