#!/usr/bin/env python
from waflib.extras import autowaf as autowaf
from waflib import Options

# Version of this package (even if built as a child)
LIBSURFACES_VERSION = '4.1.0'

# Library version (UNIX style major, minor, micro)
# major increment <=> incompatible changes
# minor increment <=> compatible changes (additions)
# micro increment <=> no interface changes
LIBSURFACES_LIB_VERSION = '4.1.0'

children = [
    'faderport',
    'faderport8',
    'cc121',
    'generic_midi',
    'mackie',
    'us2400',
    'launch_control_xl',
    'osc',
    'console1'
]

# Surfaces are hand-classified by their dependency on the bundled toolkit
# (ytk/ydk/ydk-pixbuf/ztk + libgtkmm2ext, see the root wscript).  A build without
# the toolkit (--no-tk-stack, and consequently any wasm/mobile job) builds only
# TK_FREE_CHILDREN; everything else here is a GTK widget-based surface or its
# GUI.  classify() below fails loudly on a child that is in neither list, so a
# newly added surface cannot silently break a toolkit-less build.
TK_CHILDREN = [
    'faderport',            # use = libgtkmm2ext libytkmm
    'faderport8',
    'cc121',
    'generic_midi',
    'mackie',
    'us2400',
    'launch_control_xl',
    'osc',
    'console1',
    'push2',
    'contourdesign',
    'launchpad_pro',
    'launchpad_x',
    'launchkey_4',
    'maschine2',
    'wiimote',
    'mcp_http',             # mcp_http_gui.* is Gtk:: based
]

TK_FREE_CHILDREN = [
    'websockets',           # control protocol only: glibmm + boost + libwebsockets
]

def tk_children (env, names):
    """The subset of `names` that can be built with the current toolkit availability."""
    if env['WITH_TK_STACK']:
        return list(names)
    return [n for n in names if n not in TK_CHILDREN]

def classify (conf, names):
    """Fail loudly if a surface has not been classified as tk or tk-free."""
    unknown = [n for n in names if n not in TK_CHILDREN and n not in TK_FREE_CHILDREN]
    if unknown:
        conf.fatal("libs/surfaces/wscript: unclassified surface(s): %s\n"
                   "add each one to TK_CHILDREN (uses the bundled toolkit) or to "
                   "TK_FREE_CHILDREN (does not) in libs/surfaces/wscript" % ', '.join (unknown))

def options(opt):
    pass

def configure(conf):
    global children

    autowaf.set_recursive()

    if conf.is_defined('HAVE_USB'):
        children += [ 'push2' ]
        children += [ 'contourdesign' ]
        children += [ 'launchpad_pro' ]
        children += [ 'launchpad_x' ]
        children += [ 'launchkey_4' ]

    else:
        print ('You are missing the libusb-1.0 development package needed to compile Push2 and ContourDesign support')

    if conf.is_defined('HAVE_HIDAPI') and Options.options.maschine:
        children += [ 'maschine2' ]
        conf.define('BUILD_MASCHINE', 1)

    conf.check_cc (header_name='cwiid.h', define_name='HAVE_CWIID_H',mandatory=False)
    if conf.is_defined('HAVE_CWIID_H'):
        conf.check_cc (header_name='bluetooth/bluetooth.h', define_name='HAVE_BLUETOOTH_H',mandatory=False)
        if conf.is_defined('HAVE_BLUETOOTH_H'):
            autowaf.check_pkg(conf, 'cwiid', uselib_store='CWIID', atleast_version='0.6.00',mandatory=False)
            if conf.is_defined ('HAVE_CWIID'):
                conf.define ('BUILD_WIIMOTE', 1)
                children += [ 'wiimote' ]
            else:
                print('You have the cwiid headers needed to compile wiimote support BUT you are missing the pkg-config file for cwiid')
        else:
            print('You are missing the libbluetooth headers needed to compile wiimote support')
    else:
        print('You are missing the cwiid headers needed to compile wiimote support')

    autowaf.check_pkg(conf, 'libwebsockets', uselib_store='WEBSOCKETS', atleast_version='2.0.0', mandatory=False)
    if conf.is_defined('HAVE_WEBSOCKETS'):
        children += [ 'websockets' ]
        children += [ 'mcp_http' ]

    classify (conf, children)

    for i in tk_children (conf.env, children):
        conf.recurse(i)

def build(bld):
    todo = [ 'generic_midi', 'faderport', 'faderport8', 'cc121', 'mackie',
             'us2400', 'launch_control_xl', 'osc', 'console1' ]

    if bld.is_defined('BUILD_WIIMOTE'):
        todo += [ 'wiimote' ]
    if bld.is_defined('HAVE_USB'):
        todo += [ 'push2', 'contourdesign', 'launchpad_pro', 'launchpad_x', 'launchkey_4' ]
    if bld.is_defined('BUILD_MASCHINE'):
        todo += [ 'maschine2' ]
    if bld.is_defined ('HAVE_WEBSOCKETS'):
        todo += [ 'websockets', 'mcp_http' ]

    for i in tk_children (bld.env, todo):
        bld.recurse(i)

    skipped = [i for i in todo if i not in tk_children (bld.env, todo)]
    if skipped:
        print ('Not building toolkit-based surfaces: %s' % ', '.join (skipped))
